name: Build and Push Docker Images

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          # Remove the 'v' prefix if it exists, e.g., v1.2.3 -> 1.2.3
          echo "GITHUB_REF=${GITHUB_REF}"
          echo ""VERSION=${GITHUB_REF#refs/tags/}""
          echo "VERSION=${GITHUB_REF#refs/tags/}" | sed 's/^v//' >> $GITHUB_ENV

      - name: Build CPU image
        run: docker build -f docker/cpu/Dockerfile.cpu -t transformerlab/api:${VERSION} .

      - name: Build GPU image
        run: docker build -f docker/gpu/nvidia/Dockerfile.cuda -t transformerlab/api:${VERSION}-cuda .

      - name: Push CPU image
        run: docker push transformerlab/api:${VERSION}

      - name: Push GPU image
        run: docker push transformerlab/api:${VERSION}-cuda
